from itertools import product
import spacy

from Python.utils.miscellaneous import (
    read_json,
    convert_key_list_value_of_dict,
    convert_key_str_value_of_dict,
)

DATASETS_OPENHAB_PATH_S = "Datasets/OpenHAB"
DATASETS_IFTTT_PATH_S = "Datasets/IFTTT"

EXAMPLES_SMARTTHINGS_PATH_S = "Examples/SmartThings"
EXAMPLES_IFTTT_PATH_S = "Examples/IFTTT"
EXAMPLES_OPENHAB_PATH_S = "Examples/OpenHAB"

FILES_EXAMPLES_PATH_S = "Files/Examples"
FILES_DATASETS_PATH_S = "Files/Datasets"
FILES_REFERENCE_PATH_S = "Files/Reference"
FILES_RESULTS_PATH_S = "Files/Results"
FILES_TEMPORARY_PATH_S = "Files/Temporary"

OUTPUTS_PATH_S = "Outputs"

CASE_STUDY_APPS_D = {
    "P1": "StrobeWhenIamHomeandSomeoneArrives.groovy",
    "P2": "TurnOnWhenDoorUnlocks.groovy",
    "P3": "ItsTooHot.groovy",
    "P4": "ready-for-rain.groovy",
    "P5": "DoorOpenWarningLight.groovy",
    "P6": "Notifymewhenmotionstopsformorethan2minutes.groovy",
    "P7": "initial-state-event-streamer.groovy",
    "I1": "turn-on-my-hue-light-when-i-get-out-of-bed",
    "I2": "turn-heater-on-with-a-smartthings-switch",
    "O1": "turn off your A/C after leaving home@example.rules#example",
}

CASE_STUDY_CASES_D = {
    "original": ["P1", "P2", "P3", "P4", "P5", "P6", "I1"],
    "malicious1": ["P1", "P2", "P7"],
    "malicious2": ["P3", "O1"],
    "malicious3": ["P2", "P3", "I2"],
    "both": ["P1", "P2", "P3", "P4", "P5", "P6", "I1", "I2"],
}

TEST_FAT_APP_S = (
    "initial-state-event-streamer[SmartThingsCommunity@SmartThingsPublic].groovy"
)

SMARTTHINGS_REFERENCE_D = read_json(
    f"{FILES_REFERENCE_PATH_S}/SmartThings_Reference.json"
)

OFFICIAL_APPS_S = "SmartThingsCommunity@SmartThingsPublic"
IOTBENCH_APPS_S = "IoTBench@IoTBench-test-suite"

NUM_FAT_DEVICES = 10

THETA_DIRECT_F = 1
THETA_IMPLICIT_F = 0.5

OPERATION_D = {
    "==": "!=",
    "=~": "!=",
    "!=": "==",
    ">=": "<=",
    "<=": ">=",
    ">": "<",
    "<": ">",
}
LOGICAL_D = {"&&": "||", "||": "&&"}

SUBSCRIBE_SM_METHOD_L = [
    "subscribe",
    "subscribeToCommand",
]

SCHEDULE_SM_METHOD_L = [
    "schedule",
]

RUNONCE_SM_METHOD_L = [
    "runIn",
    "runOnce",
]

RUNEVERY_SM_METHOD_L = [
    "runEvery1Minutes",
    "runEvery5Minutes",
    "runEvery10Minutes",
    "runEvery15Minutes",
    "runEvery30Minutes",
    "runEvery1Hour",
    "runEvery3Hours",
]

SINK_SM_MSG_L = [
    "sendEvent",
    "sendNotification",
    "sendLocationEvent",
    "sendMessage",
    "sendNotifications",
    "sendNotificationEvent",
    "sendNotificationToContacts",
    "sendPush",
    "sendPushMessage",
    "sendSms",
    "sendSmsMessage",
    "sendTextMessage",
]

SINK_SM_HTTP_L = [
    "httpDelete",
    "httpGet",
    "httpHead",
    "httpPost",
    "httpPostJson",
    "httpPut",
    "httpPutJson",
    "httpError",
]

SINK_IF_MSG_L = [
    "android_messages",
    "if_notifications",
    "phone_call",
    "sms",
    "voip_calls",
]

SINK_IF_HTTP_L = [
    "adafruit",
    "fitbit",
    "ifttt",
    "lightwaverf_events",
    "welltory",
]
SINK_IF_API_L = [
    "dropbox",
    "email",
    "facebook",
    "foxnews",
    "github",
    "gmail",
    "google_calendar",
    "google_sheets",
    "instagram",
    "ios_calendar",
    "ios_photos",
    "ios_reminders",
    "nytimes",
    "office_365_calendar",
    "office_365_mail",
    "reddit",
    "telegram",
    "tumblr",
    "twitch",
    "twitter",
    "uhoo",
    "youtube",
    "zoom",
]

EVENT_OP_METHOD_L = ["sendCommand", "postUpdate"]

SINK_OP_MSG_L = [
    "pushNotification",
    "sendBroadcastNotification",
    "sendHABotNotification",
    "sendLogNotification",
    "sendNotification",
    "sendPriorityMessage",
    "sendPushoverMessage",
    "sendXbmcNotification",
]

SINK_OP_HTTP_L = [
    "sendHttpDeleteRequest",
    "sendHttpGetRequest",
    "sendHttpPostRequest",
    "sendHttpPutRequest",
    "sendHttpRequest",
]

SINK_OP_API_L = [
    "sendMail",
    "sendTelegram",
    "sendTelegramAnswer",
    "sendTelegramQuery",
    "sendTweet",
]

# Temperature
# Luminance
# Motion
# Humidity
# Leakage
# Smoke
# Sound
# Power/Battery

PHYSICAL_ACTUATORS_L = [
    ["dehumidifier", "fan", "humidifier", "vent"],
    ["faucet", "sprayer", "sprinkler", "valve"],
    ["location"],
    ["light"],
    ["blind", "curtain", "cleaner", "door", "fan", "garage", "gate", "mop", "window"],
    ["conditioner", "cooler", "fireplace", "heater", "kettle", "stove", "oven"],
    ["fireplace", "heater", "purifier", "stove", "oven"],
    ["alarm", "player", "soundbar", "speaker", "tv"],
    [
        "conditioner",
        "cooler",
        "fan",
        "fireplace",
        "heater",
        "stove",
        "oven",
        "thermostat",
    ],
]
PHYSICAL_SENSORS_L = [
    ["humidity"],
    ["water"],
    ["presence"],
    ["illuminance"],
    ["motion"],
    ["gas", "power"],
    ["dioxide", "smoke", "monoxide"],
    ["sound"],
    ["temperature"],
]
PHYSICAL_CHANNEL_L = []
for idx_i in range(len(PHYSICAL_SENSORS_L)):
    PHYSICAL_CHANNEL_L.extend(
        list(product(PHYSICAL_ACTUATORS_L[idx_i], PHYSICAL_SENSORS_L[idx_i]))
    )

PRIVACY_ABBREV_D = {
    "Identification": "A",
    "Localization && Tracking": "B",
    "Activity Profiling": "C1",
    "Health Profiling": "C2",
    "Lifecycle Transitions": "D",
}

ABBREV_PRIVACY_D = convert_key_str_value_of_dict(PRIVACY_ABBREV_D)

NLP = spacy.load("en_core_web_md")

PRIVACY_INDEX_D = {
    "Identification": 0,
    "Localization && Tracking": 1,
    "Activity Profiling": 2,
    "Health Profiling": 3,
    "Lifecycle Transitions": 4,
}
LABEL_CLUSTER_D = {
    "Identification": ["Monitoring"],
    "Localization && Tracking": [
        "Activity",
        "Appliance",
        "Car",
        "Door",
        "Location",
        "Lock",
        "Monitoring",
        "Music",
        "Presence",
    ],
    "Activity Profiling": [
        "Activity",
        "Appliance",
        "Car",
        "Monitoring",
        "Music",
    ],
    "Health Profiling": ["Fitness", "Health"],
    "Lifecycle Transitions": ["Health", "Location", "Monitoring"],
}

CLUSTER_DEVICE_D = {
    "Activity": ["activity", "bathtub", "bed", "shower", "sleep"],
    "Appliance": [
        "appliance",
        "blender",
        "blind",
        "boiler",
        "cleaner",
        "coffee",
        "conditioner",
        "cooker",
        "cooktop",
        "cooler",
        "curtain",
        "dishwasher",
        "dryer",
        "fan",
        "faucet",
        "fireplace",
        "freezer",
        "fryer",
        "heater",
        "kettle",
        "light",
        "microwave",
        "mop",
        "mower",
        "oven",
        "printer",
        "projector",
        "refrigerator",
        "stove",
        "tv",
        "vacuum",
        "washer",
    ],
    "Car": ["car", "vehicle"],
    "Door": ["door", "garage", "gate", "window"],
    "Fitness": ["step", "watch", "wristband"],
    "Health": ["body", "health", "medicine"],
    "Location": ["geolocation"],
    "Lock": ["lock"],
    "Monitoring": ["camera", "audio", "image", "speech", "video"],
    "Music": ["player", "soundbar", "speaker"],
    "Presence": ["location", "occupancy", "presence"],
}

DEVICE_NOUN_D: dict = {
    "accelerometer": ["acceleration", "accelerometer", "vibrate", "vibration"],
    "activity": [
        "activity",
        "awake",
        "bath",
        "bedtime",
        "breakfast",
        "dining",
        "dinner",
        "draw",
        "lunch",
        "routine",
        "shower",
        "vacation",
        "wake",
        "waketime",
        "walk",
        "walkway",
    ],
    "alarm": ["alarm", "siren"],
    "appliance": ["appliance"],
    "audio": ["audio"],
    "bathtub": ["bathtub"],
    "battery": ["battery"],
    "beacon": ["beacon"],
    "bed": ["bed", "bedin"],
    "blender": ["blender"],
    "blind": ["blind"],
    "body": ["body", "height", "weight"],
    "boiler": ["boil", "boiler"],
    "button": ["button", "press"],
    "buzzer": ["buzzer"],
    "cabinet": ["cabinet"],
    "camera": [
        "arm",
        "armed",
        "arming",
        "camera",
        "image",
        "photo",
        "picture",
        "recording",
    ],
    "calendar": ["calendar"],
    "car": ["bus", "car", "drive", "driver", "driveway", "engine", "truck"],
    "charger": ["charger"],
    "chime": ["chime"],
    "cleaner": ["clean", "cleaner", "cleaning", "robot"],
    "clock": ["clock"],
    "coffee": ["coffee"],
    "computer": ["computer", "pc"],
    "conditioner": ["ac", "air", "conditioner"],
    "cooker": ["cook", "cooker", "cooking", "multicooker"],
    "cooktop": ["cooktop"],
    "cooler": ["cool", "cooler", "cooling"],
    "couch": ["couch"],
    "cube": ["cube"],
    "curtain": ["curtain"],
    "dehumidifier": ["dehumidification", "dehumidifier"],
    "dioxide": ["dioxide"],
    "dishwasher": ["dish", "dishwasher"],
    "door": ["door", "knock", "knocker"],
    "doorbell": ["bell", "doorbell"],
    "drawer": ["drawer"],
    "dresser": ["dresser"],
    "dryer": ["dry", "dryer"],
    "dust": ["dust"],
    "dustbin": ["dustbin"],
    "email": ["email"],
    "environment": ["environment"],
    "event": ["event", "events"],
    "fan": ["fan", "fanon"],
    "faucet": ["faucet"],
    "feeder": ["feeder", "feeding"],
    "fireplace": ["fire", "fireplace", "furnace"],
    "freezer": ["freeze", "freezer"],
    "fryer": ["fryer"],
    "game": ["game"],
    "garage": ["garage"],
    "gas": ["gas"],
    "gate": ["gate"],
    "gauge": ["gauge", "meter"],
    "geolocation": ["geolocation", "latitude", "locale", "locate", "longitude"],
    "gun": ["bullet", "gun"],
    "health": ["chest", "health", "heart", "heartbeat"],
    "heater": ["heat", "heater", "heating"],
    "hub": ["hub"],
    "humidity": ["hum", "humid", "humidity", "hygrometer", "moisture"],
    "humidifier": ["humidifier"],
    "illuminance": [
        "illuminance",
        "illuminant",
        "illuminate",
        "lumen",
        "luminance",
        "luminosity",
        "lux",
    ],
    "incubator": ["incubation", "incubator"],
    "kettle": ["kettle"],
    "keyboard": ["keyboard"],
    "keypad": ["keypad"],
    "light": [
        "blink",
        "bright",
        "brighten",
        "brightness",
        "bulb",
        "color",
        "colour",
        "dark",
        "darkness",
        "dim",
        "dimmer",
        "flasher",
        "flashing",
        "floodlight",
        "hue",
        "lamp",
        "lantern",
        "led",
        "light",
        "lighting",
        "lights",
        "lightness",
    ],
    "litter": ["litter"],
    "location": ["location", "mode"],
    "lock": ["lock", "locker", "locking", "unlock", "unlocking"],
    "mailbox": ["mail", "mailbox"],
    "medicine": ["blood", "breathe", "diabetic", "diagnostic", "medicine"],
    "microwave": ["microwave"],
    "mirror": ["mirror"],
    "momentary": ["momentary"],
    "monoxide": ["monoxide"],
    "mop": ["mop"],
    "motion": ["motion", "move", "movement"],
    "mower": ["mow", "mowing", "mower"],
    "nas": ["nas"],
    "notification": ["notification", "notifier", "notify"],
    "occupancy": ["occupancy", "occupant", "occupation", "occupy"],
    "odor": ["odor"],
    "ph": ["ph"],
    "outlet": ["outler", "outlet", "outlets", "plug", "unplug"],
    "oven": ["oven"],
    "oxygen": ["oxygen"],
    "phone": ["android", "ipad", "iphone", "mobile", "phone"],
    "player": [
        "bass",
        "media",
        "music",
        "phrase",
        "play",
        "playback",
        "player",
        "song",
        "voice",
    ],
    "power": [
        "consumption",
        "electric",
        "electricity",
        "energize",
        "energy",
        "power",
        "volt",
        "voltage",
        "watt",
        "wattage",
    ],
    "precipitation": ["precipitation"],
    "presence": [
        "adult",
        "arrive",
        "away",
        "grandma",
        "granny",
        "home",
        "people",
        "person",
        "presence",
        "present",
        "vacancy",
    ],
    "pressure": ["pressure"],
    "printer": ["printer"],
    "projector": ["projector"],
    "pump": ["pump"],
    "purifier": ["purifier"],
    "radiator": ["radiation", "radiator", "radon"],
    "radio": ["radio"],
    "refresher": ["refresh", "refresher"],
    "refrigerator": ["refrigeration", "refrigerator"],
    "reminder": ["reminder"],
    "roller": ["roller"],
    "router": ["router", "wifi", "wireless", "wiring"],
    "sleep": ["sleep", "sleeper", "sleeping", "snooze", "snoozer"],
    "smoke": ["smoke"],
    "sound": ["sound"],
    "soundbar": ["soundbar"],
    "speaker": ["microphone", "speak", "speaker"],
    "speech": ["speech", "synthesis", "synthesizer"],
    "sprayer": ["sprayer"],
    "sprinkler": ["irrigation", "sprinkler"],
    "step": ["pedometer", "step"],
    "stove": ["stove"],
    "switch": [
        "switch",
        "switched",
        "switcher",
        "switching",
        "switchy",
        "switches",
        "toggle",
        "toggler",
    ],
    "tag": ["tag"],
    "temperature": ["temperature"],
    "thermostat": [
        "therm",
        "thermal",
        "thermo",
        "thermometer",
        "thermos",
        "thermostat",
    ],
    "time": [
        "afternoon",
        "date",
        "dawn",
        "day",
        "days",
        "daytime",
        "evening",
        "everyday",
        "holiday",
        "midnight",
        "minute",
        "morning",
        "night",
        "nightfall",
        "nighttime",
        "time",
        "tomorrow",
        "tonight",
        "week",
        "weekday",
        "weekend",
        "year",
        "yesterday",
    ],
    "tone": ["tone"],
    "tune": ["tune", "tuning"],
    "tv": ["television", "tv"],
    "ultraviolet": ["ultraviolet"],
    "vacuum": ["vacuum"],
    "valve": ["valve"],
    "vehicle": ["vehicle"],
    "vent": ["vent", "ventilation"],
    "video": ["clip", "video"],
    "washer": ["laundry", "wash", "washer", "washing"],
    "watch": ["watch"],
    "water": ["flood", "fountain", "water", "waterer", "watering"],
    "weather": [
        "climate",
        "cloudy",
        "cold",
        "forecast",
        "forecaster",
        "rain",
        "rainbow",
        "rainfall",
        "warm",
        "warming",
        "weather",
        "wet",
        "wind",
        "winter",
    ],
    "window": ["shutter", "window"],
    "wristband": ["jawbone", "wristband"],
}

MATCH_EXCEPT_DEVICES_L = [
    "",
    "calendar",
    "dioxide",
    "event",
    "gas",
    "geolocation",
    "humidity",
    "illuminance",
    "location",
    "mode",
    "monoxide",
    "motion",
    "notification",
    "power",
    "presence",
    "smoke",
    "sound",
    "temperature",
    "time",
    "water",
    "weather",
]

CAPA_FIX_DEVICE_D: dict = {
    "capability.Alarm": "alarm",
    "capability.ContactSensor": "door",
    "capability.Energy Meter": "power",
    "capability.EnergyMeter": "power",
    "capability.IlluminanceMeasurement": "illuminance",
    "capability.Lock": "lock",
    "capability.Momentary": "momentary",
    "capability.Thermostat": "thermostat",
    "capability.airConditionerMode": "conditioner",
    "capability.airQualitySensor": "conditioner",
    "capability.airconditioner": "conditioner",
    "capability.alarm": "alarm",
    "capability.alarmSensor": "alarm",
    "capability.audioMute": "audio",
    "capability.audioNotification": "notification",
    "capability.audioTrackData": "audio",
    "capability.audioVolume": "audio",
    "capability.battery": "battery",
    "capability.beacon": "beacon",
    "capability.bulb": "light",
    "capability.capability.speechSynthesis": "speech",
    "capability.carbonDioxideMeasurement": "dioxide",
    "capability.carbonMonoxideDetector": "monoxide",
    "capability.carbonMonoxideMeasurement": "monoxide",
    "capability.contactSensor": "door",
    "capability.currentMeter": "meter",
    "capability.dishwasherMode": "dishwasher",
    "capability.dishwasherOperatingState": "dishwasher",
    "capability.doorControl": "door",
    "capability.dryerMode": "dryer",
    "capability.dryerOperatingState": "dryer",
    "capability.dustSensor": "dust",
    "capability.energyMeter": "power",
    "capability.estimatedTimeOfArrival": "time",
    "capability.fanControl": "fan",
    "capability.fanSpeed": "fan",
    "capability.garageDoorControl": "garage",
    "capability.geolocation": "geolocation",
    "capability.illuminanceMeasurement": "illuminance",
    "capability.imageCapture": "image",
    "capability.light": "light",
    "capability.locationMode": "location",
    "capability.lock": "lock",
    "capability.lockCodes": "lock",
    "capability.lockOnly": "lock",
    "capability.mediaController": "player",
    "capability.mediaInputSource": "player",
    "capability.mediaPlayback": "player",
    "capability.mediaPlaybackRepeat": "player",
    "capability.mediaPlaybackShuffle": "player",
    "capability.motion": "motion",
    "capability.motionSensor": "motion",
    "capability.music player": "player",
    "capability.musicPlayer": "player",
    "capability.notification": "notification",
    "capability.odorSensor": "odor",
    "capability.outlet": "outlet",
    "capability.ovenMode": "oven",
    "capability.ovenOperatingState": "oven",
    "capability.ovenSetpoint": "oven",
    "capability.pHMeasurement": "ph",
    "capability.phMeasurement": "ph",
    "capability.powerConsumptionReport": "power",
    "capability.powerMeter": "power",
    "capability.powerSource": "power",
    "capability.presence": "presence",
    "capability.presence sensor": "presence",
    "capability.presenceSensor": "presence",
    "capability.rapidCooling": "cooler",
    "capability.refrigerationSetpoint": "refrigerator",
    "capability.relativeHumidityMeasurement": "humidity",
    "capability.robotCleanerCleaningMode": "cleaner",
    "capability.robotCleanerMovement": "cleaner",
    "capability.robotCleanerTurboMode": "cleaner",
    "capability.samsungTV": "tv",
    "capability.securitySystem": "camera",
    "capability.sleepSensor": "sleep",
    "capability.smokeDetector": "smoke",
    "capability.soundPressureLevel": "sound",
    "capability.soundSensor": "sound",
    "capability.speechRecognition": "speech",
    "capability.speechSynthesis": "speech",
    "capability.stepSensor": "step",
    "capability.tamperAlert": "alarm",
    "capability.temperature": "temperature",
    "capability.temperatureMeasurement": "temperature",
    "capability.thermostat": "thermostat",
    "capability.thermostat ": "thermostat",
    "capability.thermostatCoolingSetpoint": "cooler",
    "capability.thermostatFanMode": "thermostat",
    "capability.thermostatHeatingSetpoint": "heater",
    "capability.thermostatMode": "thermostat",
    "capability.thermostatOperatingState": "thermostat",
    "capability.thermostatSetpoint": "thermostat",
    "capability.timedSession": "time",
    "capability.tone": "tone",
    "capability.trackingMusicPlayer": "player",
    "capability.tvChannel": "tv",
    "capability.ultravioletIndex": "ultraviolet",
    "capability.valve": "valve",
    "capability.videoCamera": "camera",
    "capability.videoCapture": "video",
    "capability.videoClips": "video",
    "capability.videoStream": "video",
    "capability.voltageMeasurement": "power",
    "capability.voltageMeter": "power",
    "capability.washerMode": "washer",
    "capability.washerOperatingState": "washer",
    "capability.waterSensor": "water",
    "capability.windowShade": "window",
    "device.ApplianceStatus": "appliance",
    "device.ArduinoFans": "fan",
    "device.CentraliteKeypad": "keypad",
    "device.EchoSpeaksDevice": "speaker",
    "device.IrisKeypad": "keypad",
    "device.JoinNotifier": "notification",
    "device.PersonStatus": "person",
    "device.PetFeederShield": "feeder",
    "device.RoomOccupancy": "presence",
    "device.SamsungRange": "android",
    "device.SimulatedPresenceSensor": "presence",
    "device.SmartRoomController": "presence",
    "device.SmartweatherStationTile": "weather",
    "device.SqueezeMusicServer": "player",
    "device.ThinkingCleaner": "cleaner",
    "device.WasherAndDryerFinishedMonitor": "washer",
    "device.arduinoSoundShield": "sound",
    "device.centraliteKeypad": "keypad",
    "device.connectedCar": "car",
    "device.doorShield": "door",
    "device.echoSpeaksDevice": "speaker",
    "device.econetVent": "vent",
    "device.flexidimmer": "dimmer",
    "device.flexihueBulb": "bulb",
    "device.garageDoorTile": "garage",
    "device.garagedoor": "garage",
    "device.jawboneUser": "jawbone",
    "device.keenHomeSmartVent": "vent",
    "device.mobilePresence": "presence",
    "device.nestCamera": "camera",
    "device.rheemEconetWaterHeater": "heater",
    "device.simulatedMotionSensor": "motion",
    "device.simulatedPresenceSensor": "presence",
    "device.smartweatherStationTile": "weather",
    "device.virtualWeatherStation": "weather",
    "device.wifiPresenceSensor": "presence",
    "device.wiserHeatingActuators": "heater",
}
CAPA_DEFAULT_DEVICE_D: dict = {
    "capability.Polling": "polling",
    "capability.Switch": "switch",
    "capability.accelerationSensor": "accelerometer",
    "capability.acrosscable12814.flairPressure": "",
    "capability.button": "button",
    "capability.color": "light",
    "capability.color control": "light",
    "capability.color temperature": "light",
    "capability.colorControl": "light",
    "capability.colorMode": "light",
    "capability.colorTemperature": "light",
    "capability.configuration": "",
    "capability.demandResponseLoadControl": "",
    "capability.execute": "",
    "capability.filterStatus": "",
    "capability.healthCheck": "",
    "capability.holdableButton": "button",
    "capability.hub": "",
    "capability.indicator": "",
    "capability.infraredLevel": "",
    "capability.liquidFlowRate": "",
    "capability.mediaPresets": "",
    "capability.polling": "polling",
    "capability.pushableButton": "button",
    "capability.refresh": "",
    "capability.relaySwitch": "switch",
    "capability.shockSensor": "",
    "capability.signalStrength": "",
    "capability.swicth": "switch",
    "capability.switch": "switch",
    "capability.switch level": "switch",
    "capability.switchLevel": "switch",
    "capability.switchState": "switch",
    "capability.threeAxis": "",
    "capability.touchSensor": "tag",
    "capability.type": "",
    "device.AeonKeyFob": "",
    "device.ApplicationRefreshButton": "button",
    "device.BlissControl ": "",
    "device.IrBlaster": "",
    "device.NanoleafAuroraSmarterAPI": "",
    "device.Nest": "",
    "device.Plantlink": "",
    "device.PlantlinkDirectSensor": "",
    "device.VirtualContainer": "",
    "device.aeonKeyFob": "",
    "device.arduinoRelayBoard": "",
    "device.arduinoThingShield": "",
    "device.blindsVirtualSwitch": "switch",
    "device.carwings": "",
    "device.condorShield": "",
    "device.cosmicpuppyVirtualSwitch": "switch",
    "device.dummyswitch": "switch",
    "device.easyrollsingle": "",
    "device.harmonyAPI-DeviceHandler": "",
    "device.myAutomaticDevice": "",
    "device.myEcobeeDevice": "",
    "device.myirbridge": "",
    "device.nest": "",
    "device.netatmoAdditionalModule": "",
    "device.netatmoBasestation": "",
    "device.onOffButtonTile": "button",
    "device.pico": "",
    "device.placeholder": "",
    "device.poolswitch": "switch",
    "device.pushbullet": "bullet",
    "device.smartSenseMulti": "",
    "device.switch": "switch",
    "device.tasmota": "",
    "device.totalconnectAutomationDevice": "",
    "device.totalconnectDevice": "",
    "device.totalconnectOpenCloseSensor": "",
    "device.virtualContact": "door",
    "device.virtualMultiSensor": "",
    "device.virtualSwitch": "switch",
    "device.wiserRadiatorThermostat": "thermostat",
    "device.wiserThermostatRts": "thermostat",
    "device.zwaveMeteringSwitch": "switch",
}

IFTTT_FIX_DEVICE_D: dict = {
    "SamsungRobotVacuum": "cleaner",
    "SamsungWasher": "washer",
    "WithingsSleep": "bed",
    "ambient_weather": "weather",
    "ambiclimate": "thermostat",
    "android_battery": "battery",
    "android_device": "android",
    "android_phone": "android",
    "android_photos": "camera",
    "asusrouter": "router",
    "broadlink": "tv",
    "fujitsu_general_limited": "thermostat",
    "flic": "button",
    "ge_appliances_washer": "washer",
    "google_assistant": "player",
    "google_calendar": "calendar",
    "office_365_calendar": "calendar",
    "hc_coffee_machine": "coffee",
    "hc_dishwasher": "dishwasher",
    "hc_dryer": "dryer",
    "hc_fridge": "refrigerator",
    "hc_oven": "oven",
    "hc_washer": "washer",
    "heatmiser": "heater",
    "heatzy": "heater",
    "hive_active_heating": "heater",
    "honeywell_total_connect_comfort": "thermostat",
    "hue": "light",
    "ialarmxr": "alarm",
    "intesishome": "thermostat",
    "lifx": "light",
    "location": "location",
    "mysa_thermostat": "thermostat",
    "nest_cam": "camera",
    "nest_thermostat": "thermostat",
    "netatmo_security": "camera",
    "netatmo_thermostat": "thermostat",
    "nVent_Nuheat": "thermostat",
    "oco_camera": "camera",
    "scoutalarm": "alarm",
    "somfy_thermostat": "thermostat",
    "spotcam": "camera",
    "spotify": "player",
    "tado_air_conditioning": "conditioner",
    "tado_heating": "heater",
    "tailwind": "door",
    "vesyncIftttAirPurifier": "purifier",
    "warmup_smart_thermostat": "thermostat",
    "wattio_smarthome": "camera",
    "weather": "weather",
    "wiser_air": "thermostat",
    "wiser_heat": "heater",
    "pavlok": "alarm",
}

IFTTT_DEFAULT_DEVICE_D: dict = {
    "ATLANTIC_Cozytouch": "",
    "AduroSmart": "",
    "BG_HOME": "",
    "ComEd": "",
    "LinkJapan_eHome": "",
    "LinkShades": "",
    "MagicLight": "",
    "Magic_Home": "",
    "Optoma": "",
    "Ratoc_remocon": "",
    "SAFEBYHUB6": "",
    "SAUTER_Cozytouch": "",
    "Smitch": "",
    "THERMOR_Cozytouch": "",
    "True_Energy": "",
    "abode": "",
    "agile_octopus": "",
    "aico": "",
    "airthings": "",
    "airtouch": "",
    "alko_smart_garden": "",
    "amazon_alexa": "",
    "android_messages": "",
    "appkettle": "",
    "aquanta": "",
    "aquarea_smart_cloud": "",
    "arlo": "",
    "aros": "",
    "augusthome": "",
    "automateshades": "",
    "automateshades_v2": "",
    "automower": "",
    "bang_olufsens_beo_link_gateway": "",
    "bbox_miami": "",
    "bdrthermeagroup": "",
    "beam": "",
    "bernafon": "",
    "blink": "",
    "blink1": "",
    "blink_eu": "",
    "bluebyadt": "",
    "bond": "",
    "boundary": "",
    "caavo": "",
    "caleo": "",
    "cisco_spark": "",
    "clova": "",
    "coqon": "",
    "daikin_online_controller": "",
    "danalock": "",
    "daskeyboardq": "",
    "date_and_time": "",
    "digitalstrom": "",
    "dlink_motion_sensor": "",
    "do_button": "",
    "dominos": "",
    "domovea": "",
    "dooya_connector": "",
    "dropbox": "",
    "ecobee": "",
    "eight": "",
    "electrolux": "",
    "email": "email",
    "energeasyconnect": "",
    "energenie_mi_home": "",
    "evernote": "",
    "ewelink": "",
    "ezviz": "",
    "facebook": "",
    "fansync": "",
    "fcu_tod": "",
    "feed": "",
    "fibaro": "",
    "finance": "",
    "fitbit": "",
    "foobot": "",
    "foxnews": "",
    "futurehome": "",
    "garadget": "",
    "garageio": "",
    "garagewifi": "",
    "gardena_smart_system": "",
    "ge_appliances_cooking": "",
    "ge_appliances_wac": "",
    "genius_hub": "",
    "github": "",
    "gmail": "",
    "go": "",
    "gogogate": "",
    "google_sheets": "",
    "google_wifi": "",
    "govee": "",
    "green_light_signal": "",
    "hager_iot": "",
    "harmony": "",
    "hc_cook_processor": "",
    "hc_hob": "",
    "hc_hood": "",
    "hearlink": "",
    "hive_active_light": "",
    "hive_active_plug": "",
    "hive_active_thermostat": "",
    "hive_motion_sensor": "",
    "hive_view": "",
    "home8": "",
    "home_navigation": "",
    "homeseer": "",
    "homey": "",
    "honeywell_evohome": "",
    "honeywell_lyric": "",
    "honeywell_round": "",
    "hubitat": "",
    "idevices": "",
    "if_notifications": "",
    "ihome_enhance": "",
    "indegoconnect": "",
    "instagram": "",
    "invoxia_triby": "",
    "ios_calendar": "",
    "ios_photos": "",
    "ios_reminders": "",
    "iottysmarthome": "",
    "irobot": "",
    "isitchristmas": "",
    "ispy_agent": "",
    "ivideon": "",
    "jaguar_watches": "",
    "kasa": "",
    "knocki": "",
    "kronaby": "",
    "lametric": "",
    "leeo": "",
    "legrand_home_control": "",
    "liebherr": "",
    "lightwaverf_events": "",
    "lightwaverf_heating": "",
    "lightwaverf_lighting": "",
    "lightwaverf_power": "",
    "littlebits": "",
    "livisi": "",
    "logitech_circle": "",
    "lutron_caseta_wireless": "",
    "maestro_by_stelpro": "",
    "magichue": "",
    "manything": "",
    "meross": "",
    "mesh": "",
    "migo": "",
    "misfit": "",
    "moniai": "",
    "moodo": "",
    "my_leviton": "",
    "mydlink": "",
    "myfox_homecontrol": "",
    "myq_devices": "",
    "mystrom": "",
    "nanoleaf": "",
    "nature": "",
    "neato": "",
    "nefit_easy": "",
    "nest_protect": "",
    "netatmo": "",
    "netro": "",
    "nexia": "",
    "nexx": "",
    "nibe_uplink": "",
    "nice": "",
    "nikohomecontrol": "",
    "noonhome": "",
    "notion": "",
    "nuki": "",
    "nuki_opener": "",
    "nytimes": "",
    "office_365_mail": "",
    "oge": "",
    "ohmconnect": "",
    "oticon": "",
    "pebblebee": "",
    "phone_call": "",
    "pivot_power_genius": "",
    "pocket": "",
    "powerview": "",
    "propublica": "",
    "rachio_iro": "",
    "rain_machine": "",
    "reddit": "",
    "rescuetime": "",
    "resideo_total_connect": "",
    "ring": "",
    "sRemo": "",
    "safetrek": "",
    "sengled": "",
    "sense_energy_monitor": "",
    "sensibo": "",
    "sesame": "",
    "simcam": "",
    "skybell": "",
    "skylinknet": "",
    "smanos": "",
    "smarter": "",
    "smartlife": "",
    "sms": "",
    "soma": "",
    "somfy_connexoon": "",
    "somfy_connexoon_asia_oceania": "",
    "somfy_mylink": "",
    "somfy_protect": "",
    "somfy_tahoma": "",
    "somfy_tahoma_bee": "",
    "sonic": "",
    "sonos": "",
    "space": "",
    "spotter": "",
    "stacklighting": "",
    "strava": "",
    "sunrise_sunset_org": "",
    "switchbot": "",
    "tado_hot_water": "",
    "telegram": "",
    "telldus": "",
    "tmt_chow": "",
    "todoist": "",
    "tplink_router": "",
    "trello": "",
    "tumblr": "",
    "twitch": "",
    "twitter": "",
    "uber": "",
    "uhoo": "",
    "us_independence_day": "",
    "vaillant": "",
    "vesync": "",
    "vesyncBulb": "",
    "vesyncSwitchOnline": "",
    "view_prod": "",
    "voip_calls": "",
    "watts": "",
    "weatherflow": "",
    "welltory": "",
    "wemo_coffeemaker": "coffee",
    "wemo_dimmer": "light",
    "wemo_insight_switch": "switch",
    "wemo_light_switch": "switch",
    "wemo_lighting": "",
    "wemo_maker": "",
    "wemo_motion": "motion",
    "wemo_switch": "switch",
    "whisker": "",
    "wifiplug": "",
    "wink_shortcuts": "",
    "wirelesstag": "",
    "withings": "",
    "withingshome": "",
    "wiz": "",
    "workflow": "",
    "wyzecam": "",
    "yeelight": "",
    "youtube": "",
    "zoom": "",
    "zware": "",
}


OPENHAB_FIX_DEVICE_D: dict = {
    "Battery": "battery",
    "CleaningRobot": "cleaner",
    "Humidity": "humidity",
    "Rain": "weather",
    "Snow": "weather",
    "Sun_Clouds": "weather",
    "Temperature": "temperature",
    "Time": "time",
    "Wind": "weather",
    "ac_mode": "conditioner",
    "alarm": "alarm",
    "audio": "audio",
    "bath": "bathtub",
    "bath ": "bathtub",
    "battery": "battery",
    "battery-100": "battery",
    "batterylevel": "battery",
    "bell": "bell",
    "blinds": "blind",
    "brightness": "light",
    "camera": "camera",
    "carbondioxide": "dioxide",
    "climate": "weather",
    "clock": "clock",
    "clock-on": "clock",
    "clouds": "weather",
    "color": "light",
    "colorlight": "light",
    "colorpicker": "light",
    "colortemperature": "light",
    "colorwheel": "light",
    "computer": "computer",
    "cpu": "computer",
    "currentpower": "power",
    "currentpowerCost": "power",
    "dimmablelight": "light",
    "dishwasher": "dishwasher",
    "door": "door",
    "echodot": "player",
    "efergy": "power",
    "electricity": "power",
    "energy": "power",
    "energy_green": "power",
    "energy_red": "power",
    "energymonitor": "power",
    "fan": "fan",
    "fan_ceiling": "fan",
    "faucet": "faucet",
    "fire": "fire",
    "fireLED": "light",
    "frontdoor": "door",
    "garage": "door",
    "garagedoor": "door",
    "gas": "gas",
    "googlehomemini": "player",
    "heater": "heater",
    "heater_display": "heater",
    "heating": "heater",
    "heating-40": "heater",
    "heating-60": "heater",
    "heating-off": "heater",
    "heatingseason": "heater",
    "heatingt": "heater",
    "hue": "light",
    "humidity": "humidity",
    "ilumination": "illuminance",
    "ipad": "ipad",
    "laundry": "washer",
    "lawnmower": "mower",
    "ledstrip": "light",
    "light": "light",
    "light-on": "light",
    "light_led": "light",
    "light_led_stripe": "light",
    "lightbulb": "light",
    "lightness": "light",
    "lightning": "light",
    "lights": "light",
    "lightsensor": "light",
    "lightstrip": "light",
    "location": "location",
    "lock": "lock",
    "lowbattery": "battery",
    "mobilephone": "phone",
    "motion": "motion",
    "movecontrol": "motion",
    "music": "player",
    "mute": "player",
    "nas": "nas",
    "nintendoswitch": "game",
    "oil": "gas",
    "outdoorlight": "light",
    "outdoortemp": "temperature",
    "outlet": "outlet",
    "overallpower": "power",
    "overallpowerCost": "power",
    "paneloven": "oven",
    "phone": "phone",
    "playback2": "player",
    "player": "player",
    "plex": "player",
    "power": "power",
    "poweroutlet": "outlet",
    "poweroutlet_eu": "outlet",
    "poweroutlet_us": "outlet",
    "presence": "presence",
    "present": "presence",
    "pressure": "pressure",
    "printer": "printer",
    "pump": "pump",
    "radiator": "vent",
    "rain": "weather",
    "rollershuter": "window",
    "rollershutter": "window",
    "selfClock": "clock",
    "selfenergy": "power",
    "selftelevision": "tv",
    "senseo_brewed_size": "coffee",
    "senseo_coffeesign": "coffee",
    "senseo_cup_avail": "coffee",
    "senseo_cup_big": "coffee",
    "senseo_cup_content": "coffee",
    "senseo_machine": "coffee",
    "senseo_milkjug": "coffee",
    "senseo_tamper": "coffee",
    "siren": "alarm",
    "smartheater": "heater",
    "smartheater-on": "heater",
    "smoke": "smoke",
    "snow": "weather",
    "socket": "outlet",
    "solarplant": "power",
    "sonoff_basic": "player",
    "sonos": "player",
    "sonos3": "player",
    "sonos_add": "player",
    "sonos_alarm": "player",
    "sonos_alarm_prop": "player",
    "sonos_album": "player",
    "sonos_artist": "player",
    "sonos_control": "player",
    "sonos_coordinator": "player",
    "sonos_favorite": "player",
    "sonos_led": "player",
    "sonos_mute": "player",
    "sonos_notification": "player",
    "sonos_play_track": "player",
    "sonos_play_uri": "player",
    "sonos_playlist": "player",
    "sonos_publiv": "player",
    "sonos_que": "player",
    "sonos_radio": "player",
    "sonos_remove": "player",
    "sonos_repeat": "player",
    "sonos_restore": "player",
    "sonos_restore_all": "player",
    "sonos_save": "player",
    "sonos_save_all": "player",
    "sonos_shuffle": "player",
    "sonos_sleep_timer": "player",
    "sonos_snooze": "player",
    "sonos_stand_alone": "player",
    "sonos_state": "player",
    "sonos_stop": "player",
    "sonos_title": "player",
    "sonos_track": "player",
    "sonos_uri": "player",
    "sonos_zone": "player",
    "sonosconnect": "player",
    "sonso_alarm_run": "player",
    "sound": "sound",
    "soundvolume": "sound",
    "soundvolume-0": "sound",
    "soundvolume_mute": "sound",
    "speaker": "speaker",
    "speaker-black": "speaker",
    "speakervol": "speaker",
    "squeezeboxclassic": "radio",
    "squeezeboxradio": "radio",
    "streammusic": "player",
    "sun_clouds": "weather",
    "television": "tv",
    "temperature": "temperature",
    "temperature_cold": "temperature",
    "temperature_hot": "temperature",
    "thermometer_red": "thermometer",
    "thermometer_red_earth": "thermometer",
    "thermostat_heater": "heater",
    "time": "time",
    "tv": "tv",
    "tvremoteMD32": "tv",
    "vacuum": "cleaner",
    "ventilation": "vent",
    "video": "video",
    "volume": "sound",
    "volume_mute": "sound",
    "walllamp": "light",
    "wallplug": "outlet",
    "wallswitch": "switch",
    "washingmach": "washer",
    "washingmachine": "washer",
    "water": "water",
    "waterdrop": "water",
    "waterheating": "water",
    "weather-cloudy": "weather",
    "weather-unknown": "weather",
    "wifirouter": "router",
    "wind": "weather",
    "window": "window",
    "windowcheck": "window",
    "windowsensor": "window",
}

OPENHAB_ITEM_FIX_DEVICE_D = {
    "airquality": "geolocation",
    "alexa": "player",
    "amazonechocontrol": "player",
    "astro": "geolocation",
    "benqprojector": "projector",
    "boschindego": "mower",
    "broadlink": "thermostat",
    "buienradar": "weather",
    "chromecast": "player",
    "comfoair": "conditioner",
    "daikin": "conditioner",
    "darksky": "weather",
    "deconz": "presence",
    "denon": "tv",
    "denonmarantz": "tv",
    "dsmr": "power",
    "ecobee": "thermostat",
    "ewpesmart": "conditioner",
    "freebox": "tv",
    "gpstracker": "geolocation",
    "homekit": "light",
    "homematic": "thermostat",
    "hue": "light",
    "insteon": "light",
    "insteonplm": "light",
    "ipcamera": "camera",
    "irobot": "cleaner",
    "irrigation": "irrigation",
    "kodi": "player",
    "lghombot": "cleaner",
    "lgwebos": "tv",
    "miio": "cleaner",
    "milight": "light",
    "millheat": "heater",
    "mios": "conditioner",
    "mpd": "player",
    "nest": "thermostat",
    "networkupstools": "battery",
    "ntp": "time",
    "onkyo": "tv",
    "openweathermap": "weather",
    "panasonic": "conditioner",
    "panasonictv": "tv",
    "pilight": "light",
    "pioneeravr": "tv",
    "plex": "tv",
    "samsungac": "conditioner",
    "samsungtv": "tv",
    "sinkName": "audio",
    "solaredge": "power",
    "sonos": "player",
    "sony": "player",
    "spotify": "player",
    "squeeze": "player",
    "squeezebox": "player",
    "synonyms": "conditioner",
    "tplinksmarthome": "outlet",
    "tradfri": "light",
    "valloxmv": "vent",
    "weather": "weather",
    "weatherunderground": "weather",
    "wemo": "light",
    "xbmc": "player",
    "yahooweather": "weather",
    "yamahareceiver": "player",
    "yeelight": "light",
}

STATE_VERB_D: dict = {
    "on": ["on"],
    "off": ["off"],
    "open": ["open", "opened"],
    "close": ["close", "closed"],
    "lock": ["lock", "locked"],
    "unlock": ["unlock", "unlocked"],
}

NORMALIZE_VALUE_D: dict = {
    "on": [">", ">=", "on", "open", "unlock", "active", "wet", "present"],
    "off": ["<", "<=", "off", "close", "lock", "inactive", "dry", "not present"],
}

VALUE_DIFFERENT_DEVICES_L: list = [
    ("dehumidifier", "humidity"),
    ("fan", "humidity"),
    ("vent", "humidity"),
    ("purifier", "dioxide"),
    ("purifier", "smoke"),
    ("purifier", "monoxide"),
    ("cooler", "temperature"),
    ("fan", "temperature"),
]

VALUE_WHATEVER_DEVICES_L: list = [
    ("conditioner", "temperature"),
    ("thermostat", "temperature"),
]
ANTONYMY_VERB_D: dict = {
    "on": ["off"],
    "off": ["on"],
    "open": ["close", "closed"],
    "close": ["open", "opened"],
    "lock": ["unlock", "unlocked"],
    "unlock": ["lock", "locked"],
    "present": ["not present"],
    "not present": ["present"],
    "active": ["inactive"],
    "inactive": ["active"],
}

NOUN_DEVICE_D: dict = convert_key_list_value_of_dict(DEVICE_NOUN_D)
VERB_STATE_D: dict = convert_key_list_value_of_dict(STATE_VERB_D)
VALUE_NORMALIZE_D: dict = convert_key_list_value_of_dict(NORMALIZE_VALUE_D)
VERB_ANTONYMY_D: dict = convert_key_list_value_of_dict(ANTONYMY_VERB_D)

CLUSTER_LABEL_D = {}
for label_s, cluster_l in LABEL_CLUSTER_D.items():
    for cluster_s in cluster_l:
        if cluster_s not in CLUSTER_LABEL_D:
            CLUSTER_LABEL_D[cluster_s] = []
        CLUSTER_LABEL_D[cluster_s].append(label_s)

DEVICE_LABEL_D = {}
for cluster_s, device_l in CLUSTER_DEVICE_D.items():
    for device_s in device_l:
        DEVICE_LABEL_D[device_s] = CLUSTER_LABEL_D[cluster_s]
